version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/maestrod/main.go
    binary: maestrod
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64

archives:
  - name_template: >-
      maestrod_ 
      {{- trimprefix .Version "." }}_
      {{- if eq .Os "darwin" }}Darwin_
      {{- else if eq .Os "linux" }}Linux_
      {{- else if eq .Os "windows" }}Windows_
      {{- else }}{{ .Os }}_{{end}}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
