name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow on tag push (e.g., v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # allows downloading code from repo
      packages: read  # needed to access GitHub packages
      id-token: write  # required for authentication with GitHub Packages (private)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.11'

      - name: Authenticate with GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          go env -w GOPRIVATE=github.com/s16rv/*  # Replace with your org name

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

